[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@manifoldxyz/=lib/@manifoldxyz/',
    '@openzeppelin/=lib/@openzeppelin/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config