[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@manifoldxyz/libraries-solidity/=lib/libraries-solidity/',
    '@manifoldxyz/creator-core-solidity/=lib/creator-core-solidity/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config